package im.whj.cn.im_ui.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import im.whj.cn.im_ui.db.entity.MsgDbModel;

import im.whj.cn.im_ui.db.MsgDbModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgDbModelDaoConfig;

    private final MsgDbModelDao msgDbModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgDbModelDaoConfig = daoConfigMap.get(MsgDbModelDao.class).clone();
        msgDbModelDaoConfig.initIdentityScope(type);

        msgDbModelDao = new MsgDbModelDao(msgDbModelDaoConfig, this);

        registerDao(MsgDbModel.class, msgDbModelDao);
    }
    
    public void clear() {
        msgDbModelDaoConfig.clearIdentityScope();
    }

    public MsgDbModelDao getMsgDbModelDao() {
        return msgDbModelDao;
    }

}
